sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t lobhas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lobhas/docker-react npm run test

deploy:
  provider: digitalocean
  region: "lon-1"
  app: "docker-react"
  env: "Docker-env"
  on:
    branch: master
